name: Target Workflow
run-name: Receiving from Workflow parent runID ${{github.event.client_payload.distinct_id }}
on:
  repository_dispatch:
    types: [trigger-workflow]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ github.event.client_payload.artifactURL }}'

      - name: Download K6 Artifact
        run: |
          # Set the required variables
          repo_owner="rossi-labs" 
          repo_name="worflowremote"  
          event_type="trigger-workflow"
          artifactURL="${{ github.event.client_payload.artifactURL }}"
  
          curl -L --output k6.zip \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$artifactURL"

      - name: Check K6 artifact
        run: file k6.zip

      - name: unzip K6 artifact
        run: unzip k6.zip
        
      - name: list K6 artifact
        run: ls -ilha .
