name: Trigger Target Workflow

on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: rossi-labs
      REPO_NAME: worflowremote

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        id: artifact-k6-upload
        with:
          name: k6test-${{ github.run_id }}
          path: k6_test
          
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ steps.artifact-k6-upload.outputs.artifact-url }}'
      
      - name: Trigger Workflow in Another Repository
        run: |  
          event_type="trigger-workflow"
          distinct_id="${{ github.run_id }}"
          artifactURL="https://api.github.com/repos/${{github.repository}}/actions/artifacts/${{steps.artifact-k6-upload.outputs.artifact-id}}/zip"
          
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"artifactURL\": \"$artifactURL\", \"distinct_id\": \"$distinct_id\"}}"     

      - name: Get remote workflow status 
        run: |
          distinct_id="${{ github.run_id }}"
          completed=false
          
          sleep 10 && \
          target_workflow_id=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows \
            | jq -r '.workflows[] |select(.name=="Target Workflow") | .id') && \
          remote_distinct_id=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$target_workflow_id/runs \
            | jq -r ".workflow_runs[] |select(.name | contains(\"$distinct_id\")) | .id") && \
          for i in {1..30}; do # Tentativa de 30 vezes com espera de 5 segundos entre elas.
          echo "Checking workflow run status attempt $i"
          status=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.access-token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$remote_distinct_id | jq -r ".status")
      
          if [[ "$status" == "completed" ]]; then
              echo "Workflow completed"
              break
          else
              echo "Workflow status: $status. Waiting..."
              sleep 5
          fi
          done
          
          if [[ "$status" != "completed" ]]; then
              echo "Workflow did not complete in time"
              exit 1
          fi
      
      - name: Download K6 Logs
        run: |
          target_workflow_id=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows \
            | jq -r '.workflows[] |select(.name=="Target Workflow") | .id') && \
          remote_distinct_id=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$target_workflow_id/runs \
            | jq -r ".workflow_runs[] |select(.name | contains(\"$distinct_id\")) | .id") && \
          artifactURL=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.access-token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$remote_distinct_id \
              | jq -r ".artifacts_url") && \
          archive_download_url=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$artifactURL" \
            | jq -r ".artifacts[] |select(.name | contains(\"k6test_logs-\")) | .archive_download_url") && \
          curl -L --output k6.zip \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$archive_download_url"
  
      - name: Check K6 artifact
        run: file k6.zip

      - name: unzip K6 artifact
        run: unzip k6.zip
        
      - name: list K6 artifact
        run: ls -ilha .

      - name: expose K6 logs
        run: cat k6_test.log
