name: Trigger Target Workflow

on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        id: artifact-k6-upload
        with:
          name: k6test-${{ github.run_id }}
          path: k6_test
          
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ steps.artifact-k6-upload.outputs.artifact-url }}'
      
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="rossi-labs" 
          repo_name="worflowremote"  
          event_type="trigger-workflow"
          distinct_id="${{ github.run_id }}"
          artifactURL="https://api.github.com/repos/${{github.repository}}/actions/artifacts/${{steps.artifact-k6-upload.outputs.artifact-id}}/zip"
          
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"artifactURL\": \"$artifactURL\", \"distinct_id\": \"$distinct_id\"}}"     

      - name: Ger remote workflow status 
        run: |
          repo_owner="rossi-labs" 
          repo_name="worflowremote"  
          distinct_id="${{ github.run_id }}"
          
          sleep 10 && \
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.access-token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/85381483/runs \
            | jq -r ".workflow_runs[] |select(.name | contains(\"$distinct_id\")) | .id"
